### ISSUE TITLE
This package should be quilt-formatted

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/telepathy-mission-control-5#3]
*Someone* took the easy route of importing this repository from Debian and abusing the `native` debhelper format to get tmc-5 built. We should pay back that technical debt by finding which upstream release matches this downstream repo, then building it with a `quilt` formatted debian directory.

**Comment by peat-psuwit** [comment]
Migrated to GitLab.

https://gitlab.com/ubports/development/core/packaging/telepathy-mission-control-5/-/issues/3
